2024-02-10 23:30:57,512 - INFO - ::Connection accepted by server connect
2024-02-10 23:30:57,624 - INFO - server listening on [::1]:12260
2024-02-10 23:30:57,624 - INFO - server listening on 127.0.0.1:12260
2024-02-10 23:30:59,341 - INFO - connection open
2024-02-11 22:33:38,338 - INFO - ::Connection accepted by server connect
2024-02-11 22:33:38,488 - INFO - server listening on 127.0.0.1:12260
2024-02-11 22:33:38,488 - INFO - server listening on [::1]:12260
2024-02-11 22:33:40,466 - INFO - connection open
2024-02-11 22:43:27,163 - ERROR - ::Connection fatal ... at server.py/initiate_connection, exp : [Errno 11001] getaddrinfo failed
2024-02-11 22:55:34,059 - INFO - ::Connection accepted by server connect
2024-02-11 22:55:34,161 - INFO - server listening on 127.0.0.1:12260
2024-02-11 22:55:34,161 - INFO - server listening on [::1]:12260
2024-02-11 22:55:35,827 - INFO - connection open
2024-02-11 23:21:12,481 - ERROR - ::Connection fatal ... at server.py/initiate_connection, exp : [Errno 11001] getaddrinfo failed
